---
outlines:
    default: { width: 40, height: 60 }
    return: { width: 95, height: 60 }
    altline: { width: 40, height: 60 }
    wide: { width: 57, height: 60 }
    narrow: { width: 26, height: 60 }
    spaceline: { width: 107, height: 60 }
    fill: { width: 159, height: 60 }
    special: { width: 42, height: 60 }

views:
    base:
        - "й ц у к е н г ш щ з х"
        - "ф ы в а п р о л д ж э"
        - "Shift_L  я ч с м и т ь б ю  BackSpace"
        - "show_numbers preferences  comma  ё  space  ъ  period Return"
    upper:
        - "Й Ц У К Е Н Г Ш Щ З Х"
        - "Ф Ы В А П Р О Л Д Ж Э"
        - "Shift_L   Я Ч С М И Т Ь Б Ю  BackSpace"
        - "show_numbers preferences  comma  Ё  space  Ъ  comma Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols   , \" ' colon ; ! ?  BackSpace"
        - "show_letters preferences         space_fill   period Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers_from_symbols   \\ / < > = [ ]  BackSpace"
        - "show_letters preferences         space_fill   period Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: show_prefs
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "АБВ"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "wide"
        label: "*/="
    period:
        outline: "special"
        text: "."
    comma:
        outline: "special"
        text: ","
    space:
        outline: "spaceline"
        text: " "
    space_fill:
        outline: "fill"
        text: " "
    Return:
        outline: "return"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
    ё:
        outline: "narrow"
    Ё:
        outline: "narrow"
    ъ:
        outline: "narrow"
    Ъ:
        outline: "narrow"
