---
outlines:
    default: { width: 39.33, height: 52 }
    return: { width: 80, height: 52 }
    altline: { width: 52.67, height: 52 }
    wide: { width: 45, height: 52 }
    spaceline: { width: 142, height: 52 }
    special: { width: 40, height: 52 }

views:
    base:
        - "q w e r t y u i o p"
        - "a s d f g h j k l"
        - "Shift_L   z x c v b n m  BackSpace"
        - "show_numbers preferences     comma    space        period Return"
    upper:
        - "Q W E R T Y U I O P"
        - "A S D F G H J K L"
        - "Shift_L   Z X C V B N M  BackSpace"
        - "show_numbers preferences    comma     space        period Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols   , \" ' colon ; ! ?  BackSpace"
        - "show_letters preferences         space        period Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers_from_symbols   \\ / < > = [ ]  BackSpace"
        - "show_letters preferences         space        period Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: show_prefs
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "*/="
    period:
        outline: "special"
        text: "."
    comma:
        outline: "special"
        text: ","
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "return"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
